package com.test.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Foo service. Represents a row in the &quot;test_Foo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.servicebuilder.model.impl.FooModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.servicebuilder.model.impl.FooImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Foo
 * @see com.test.servicebuilder.model.impl.FooImpl
 * @see com.test.servicebuilder.model.impl.FooModelImpl
 * @generated
 */
public interface FooModel extends BaseModel<Foo> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a foo model instance should use the {@link Foo} interface instead.
     */

    /**
     * Returns the primary key of this foo.
     *
     * @return the primary key of this foo
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this foo.
     *
     * @param primaryKey the primary key of this foo
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this foo.
     *
     * @return the uuid of this foo
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this foo.
     *
     * @param uuid the uuid of this foo
     */
    public void setUuid(String uuid);

    /**
     * Returns the foo ID of this foo.
     *
     * @return the foo ID of this foo
     */
    public long getFooId();

    /**
     * Sets the foo ID of this foo.
     *
     * @param fooId the foo ID of this foo
     */
    public void setFooId(long fooId);

    /**
     * Returns the user name of this foo.
     *
     * @return the user name of this foo
     */
    @AutoEscape
    public String getUserName();

    /**
     * Sets the user name of this foo.
     *
     * @param userName the user name of this foo
     */
    public void setUserName(String userName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.test.servicebuilder.model.Foo foo);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.test.servicebuilder.model.Foo> toCacheModel();

    @Override
    public com.test.servicebuilder.model.Foo toEscapedModel();

    @Override
    public com.test.servicebuilder.model.Foo toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
